#Api version moet je op het internet zoeken
apiVersion: v1
#We geven aan dat dit een service config file is
kind: Service
#We geven de service een aantal eigenschappen mee
metadata:
#We geven het natuurlijk een naam
  name: nginx-service-bv
#We geven aan in wat voor namespace deze service moet komen
  namespace: default
#We gaan er dieper op in wat de service juist moet doen
spec:
#Het is een type ClusterIP, en dus alleen binnen de cluster bereikbaar
  type: ClusterIP
#We geven aan welke poort onze app gebruikt en via welke deze poort bereikbaar moet zijn op de service
  ports:
    - protocol: TCP
      port: 80 # port on the service IP
      targetPort: 80 # port on the container, can also be a number
#We gebruiken weer onze selector om te zeggen bij welke app deze service hoort
  selector:
    app: nginx
