#Api version moet je op het internet opzoeken
apiVersion: v1
#We geven aan dat dit een service config file is
kind: Service
#We geven de service een aantal eigenschappen mee
metadata:
#We geven het natuurlijk een naam
  name: db-service-bv
#We geven aan in wat voor namespace deze service moet komen
  namespace: default
#We gaan er dieper op in wat de service juist moet doen
spec:
#Het is een type ClusterIP, en dus alleen binnen de cluster bereikbaar
  type: ClusterIP
#We gebruiken weer onze selector om te zeggen bij welke app deze service hoort
  selector:
    app: database
#We geven aan welke poort onze app gebruikt en via welke deze poort bereikbaar moet zijn op de service
  ports:
    - name: mariadb
      protocol: TCP
      port: 3306
      targetPort: 3306