apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: db-volume-claim
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce