apiVersion: v1
kind: Service
metadata:
  name: api-service-bv
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000 # port on the service IP
      targetPort: 8000 # port on the container, can also be a number
  selector:
    app: api