apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-bv
  namespace: default
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: brecht404/project-app:latest
        ports:
        - containerPort: 8000